services:
  inventory_manager:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      - DB_FILE=${DB_FILE}
    ports:
      - "${API_PORT}:8080"
    volumes:
      - ./data/:/app/data/