openapi: 3.1.0
info:
  title: Inventory Manager
  description:
    Inventory Manager that stores items, manipulates their quantities, and calculates the value of inventory items.
  version: 1.0.0
paths:
  /items:
    get:
      description: Returns all items in inventory.
      responses:
        '200':
          description: Returns the items in the inventory as a JSON array of items.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
        '500':
          description: An unexpected server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /item:
    post:
      description: Adds the specified item to inventory.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Item"
      responses:
        '201':
          description: The item was added successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Item'
        '400':
          description: The given data was invalid.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: An unexpected server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /item/{id}:
    patch:
      description: Alters the quantity associated to an Item in the inventory.
      parameters:
        - name: id
          in: path
          description: The ID of the item to delete.
          required: true
          schema:
            example: 1
            type: uint
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Delta"
      responses:
        '200':
          description: Returns the updated Item on success.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Items'
        '400':
          description: The given id is not an unsigned int.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The given id was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '409':
          description: The given delta would cause the quantity to become negative.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    delete:
      description: Deletes an item from the inventory.
      parameters:
        - name: id
          in: path
          description: The ID of the item to delete.
          required: true
          schema:
            example: 1
            type: uint
      responses:
        '204':
          description: The item was deleted successfully.
        '400':
          description: The given id is not an unsigned int.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '404':
          description: The given id was not found.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '500':
          description: An unexpected server error occurred.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    Items:
      type: object
      additionalProperties:
        $ref: '#/components/schemas/Item'
      example:
        1:
          name: 'Table'
          quantity: 10
          price: 119.99
        2:
          name: 'Chair'
          quantity: 5
          price: 29.99

    Item:
      type: object
      properties:
        name:
          type: string
          example: 'Table'
          description:
            The name of the inventory item.
        quantity:
          type: integer
          format: int64
          example: 10
          description: The current quantity of the inventory item.
        price:
          type: number
          format: double
          example: 119.99
          description: The monetary value of the inventory item in euro.

    Delta:
      type: object
      properties:
        quantityDelta:
          type: integer
          format: int64
          example: -5

    Error:
      type: object
      properties:
        error:
          type: string
          example: 'Error message.'